### ISSUE TITLE
Alternative Codebase

### ISSUE THREAD

**Issue by BMDan** [madchicken/homebridge-esphome-garagedoor#6]
After several days of trying, I was not able to get this code to work.  [Current best practices](https://developers.homebridge.io/#/) recommend using the "dynamic" (i.e., "platform") plugin type.  I've built just such a plugin, using your code as reference, aimed at the RatGDO running ESPHome (the only thing that would need to change with a Shelly is the version parsing and the `Set` endpoint).  It's at https://github.com/BMDan/homebridge-ratgdo-esphome/tree/main .  Since the functionality of the two is essentially the exact same, would you be interested in switching?

**Comment by madchicken** [comment]
Hey, @BMDan can you be more specific about `I was not able to get this code to work`? Regarding your plugin, feel free to use my code in yours, no problem. I wrote this a long time ago and never changed it since it's still working with the newest versions of Homebridge.

**Comment by BMDan** [comment]
> Hey, @BMDan can you be more specific about I was not able to get this code to work? 

@madchicken : No matter how I configured it, no code would actually run inside of the accessory itself.  I even went so far as to `throw` inside of some methods, just to see if they were hit; they never were.  Admittedly, I'm on HOOBS 4.x, so perhaps there's some difference.  There were also a few weird bugs, like the fact that on shutdown, the connection would be closed, but then quickly reopened when the timeout next expired, so if you had unlucky timing, a restart would take really long while it waited for that *new* connection to be closed.

It's absolutely possible that I messed up, but I couldn't make heads or tails of why it wasn't working.  After three days of trying, I went ahead and rewrote it.  I didn't realize you were still actively using (much less maintaining) this code, so I apologize if my suggestion seemed out of place.  Instead, I'll simply point you at https://github.com/BMDan/homebridge-ratgdo-esphome/blob/main/src/discovery.ts, which represents the biggest change I made from your code: instead of registering the accessory directly, my version launches a discovery probe to get its current status, thereby allowing registration to happen only once all the information about the accessory is available and validated.

Lastly, I just wanted to say thank you for creating this project.  Even if you don't end up using any of my code in your project, having your code available to me was absolutely critical at several points in my own development process, and my project will forever owe you a debt a gratitude.

**Comment by madchicken** [comment]
Thanks, @BMDan for the code you shared, I will take a look at it. Honestly, I don't understand why it doesn't work with HOOBS, it should share the same Homebridge code under the hood 🤷‍♂️
I know there are bugs in my implementation, especially in the connection phase...I just stopped when I got to the garage door opening and closing 😄 ... I'll try to improve the codebase as soon as I have some time to spend on this
